name: Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    # Build: Self-contained
    - name: Publish Self-Contained
      run: dotnet publish -c Release -r win-x64 --self-contained true -o publish/self-contained

    # Build: Framework-dependent
    - name: Publish Framework-Dependent
      run: dotnet publish -c Release -r win-x64 --self-contained false -o publish/framework-dependent

    # Zip both outputs
    - name: Archive builds
      run: |
        Compress-Archive -Path publish/self-contained/* -DestinationPath auc-self-contained.zip
        Compress-Archive -Path publish/framework-dependent/* -DestinationPath auc-framework-dependent.zip

    # Create GitHub Release and upload zips
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          auc-self-contained.zip
          auc-framework-dependent.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
